title: Roberto Nieto Salgado
email: roberto.nieto.sal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
  Posting topics I find interesting about the IT world, also you will find some 
  things about me ;) .

twitter_username: Stealthrob1
github_username:  stealthrob
linkedin_username: robertonietosalgado

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

header_pages:
  - about.md
  - projects.md
  - video-commentary.html
  - contact.md

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - script/
  - README.md
  - LICENSE.txt
  - minima.gemspec
  - CLAUDE.md
